version: "3"
services:
        redis:
                image: redis:alpine
                ports:
                        - "6379"
                deploy:
                        replicas: 1
                        update_config:
                                parallelism: 2
                                delay: 10s
                        restart_policy:
                                condition: on-failure

        server:
                image: rnicolescu/server:test
                volumes:
                        - db-data:/var/lib/photos
                ports:
                        - 5000:5000
                depends_on:
                        - redis

        worker:
                image: rnicolescu/worker:test
                volumes:
                        - db-data:/var/lib/photos/
                depends_on:
                        - redis
                        
volumes:
 db-data: