version: "3"
services:
        redis:
                image: redis:alpine
                ports:
                        - "6379"
                networks:
                        - frontend
                deploy:
                        replicas: 1
                        update_config:
                                parallelism: 2
                                delay: 10s
                        restart_policy:
                                condition: on-failure

        server:
                image: rnicolescu/server:test
                ports:
                        - 5000:5000
                networks:
                        - frontend
                depends_on:
                        - redis

        worker:
                image: rnicolescu/worker:test
                depends_on:
                        - redis
networks:
        frontend:
        backend:
